// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.13.0
// source: developer_store.proto

package tcaplusservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ENUM_Medium int32

const (
	ENUM_Medium_official_site ENUM_Medium = 0
	ENUM_Medium_twitter       ENUM_Medium = 1
	ENUM_Medium_facebook      ENUM_Medium = 2
	ENUM_Medium_instagram     ENUM_Medium = 3
	ENUM_Medium_youtube       ENUM_Medium = 4
	ENUM_Medium_discord       ENUM_Medium = 5
)

// Enum value maps for ENUM_Medium.
var (
	ENUM_Medium_name = map[int32]string{
		0: "official_site",
		1: "twitter",
		2: "facebook",
		3: "instagram",
		4: "youtube",
		5: "discord",
	}
	ENUM_Medium_value = map[string]int32{
		"official_site": 0,
		"twitter":       1,
		"facebook":      2,
		"instagram":     3,
		"youtube":       4,
		"discord":       5,
	}
)

func (x ENUM_Medium) Enum() *ENUM_Medium {
	p := new(ENUM_Medium)
	*p = x
	return p
}

func (x ENUM_Medium) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENUM_Medium) Descriptor() protoreflect.EnumDescriptor {
	return file_developer_store_proto_enumTypes[0].Descriptor()
}

func (ENUM_Medium) Type() protoreflect.EnumType {
	return &file_developer_store_proto_enumTypes[0]
}

func (x ENUM_Medium) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENUM_Medium.Descriptor instead.
func (ENUM_Medium) EnumDescriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{0}
}

type ENUM_Status int32

const (
	ENUM_Status_Developing  ENUM_Status = 0
	ENUM_Status_Coming_Soon ENUM_Status = 1
	ENUM_Status_Experience  ENUM_Status = 2
	ENUM_Status_Released    ENUM_Status = 3
)

// Enum value maps for ENUM_Status.
var (
	ENUM_Status_name = map[int32]string{
		0: "Developing",
		1: "Coming_Soon",
		2: "Experience",
		3: "Released",
	}
	ENUM_Status_value = map[string]int32{
		"Developing":  0,
		"Coming_Soon": 1,
		"Experience":  2,
		"Released":    3,
	}
)

func (x ENUM_Status) Enum() *ENUM_Status {
	p := new(ENUM_Status)
	*p = x
	return p
}

func (x ENUM_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENUM_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_developer_store_proto_enumTypes[1].Descriptor()
}

func (ENUM_Status) Type() protoreflect.EnumType {
	return &file_developer_store_proto_enumTypes[1]
}

func (x ENUM_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENUM_Status.Descriptor instead.
func (ENUM_Status) EnumDescriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{1}
}

type DeveloperStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// primary key fields
	AppId  string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Ordinary fields
	// basic information
	Info *Developer_BasicInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	// medias
	Medias *Developer_Media `protobuf:"bytes,4,opt,name=medias,proto3" json:"medias,omitempty"`
	//Experience
	Exp *Developer_Experience `protobuf:"bytes,5,opt,name=exp,proto3" json:"exp,omitempty"`
	//build
	Builds []*Developer_BUILD `protobuf:"bytes,6,rep,name=builds,proto3" json:"builds,omitempty"`
}

func (x *DeveloperStore) Reset() {
	*x = DeveloperStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_developer_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeveloperStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeveloperStore) ProtoMessage() {}

func (x *DeveloperStore) ProtoReflect() protoreflect.Message {
	mi := &file_developer_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeveloperStore.ProtoReflect.Descriptor instead.
func (*DeveloperStore) Descriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{0}
}

func (x *DeveloperStore) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeveloperStore) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeveloperStore) GetInfo() *Developer_BasicInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *DeveloperStore) GetMedias() *Developer_Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *DeveloperStore) GetExp() *Developer_Experience {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *DeveloperStore) GetBuilds() []*Developer_BUILD {
	if x != nil {
		return x.Builds
	}
	return nil
}

// basic information
type Developer_BasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductName   string              `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductDetail string              `protobuf:"bytes,3,opt,name=product_detail,json=productDetail,proto3" json:"product_detail,omitempty"`
	Developer     string              `protobuf:"bytes,4,opt,name=developer,proto3" json:"developer,omitempty"`
	Publisher     string              `protobuf:"bytes,5,opt,name=publisher,proto3" json:"publisher,omitempty"`
	ProductStatus ENUM_Status         `protobuf:"varint,6,opt,name=product_status,json=productStatus,proto3,enum=tcaplusservice.ENUM_Status" json:"product_status,omitempty"`
	Pubdate       string              `protobuf:"bytes,7,opt,name=pubdate,proto3" json:"pubdate,omitempty"`
	Mediums       []*Developer_Medium `protobuf:"bytes,8,rep,name=mediums,proto3" json:"mediums,omitempty"`
}

func (x *Developer_BasicInfo) Reset() {
	*x = Developer_BasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_developer_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Developer_BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer_BasicInfo) ProtoMessage() {}

func (x *Developer_BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_developer_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer_BasicInfo.ProtoReflect.Descriptor instead.
func (*Developer_BasicInfo) Descriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{1}
}

func (x *Developer_BasicInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Developer_BasicInfo) GetProductDetail() string {
	if x != nil {
		return x.ProductDetail
	}
	return ""
}

func (x *Developer_BasicInfo) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *Developer_BasicInfo) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Developer_BasicInfo) GetProductStatus() ENUM_Status {
	if x != nil {
		return x.ProductStatus
	}
	return ENUM_Status_Developing
}

func (x *Developer_BasicInfo) GetPubdate() string {
	if x != nil {
		return x.Pubdate
	}
	return ""
}

func (x *Developer_BasicInfo) GetMediums() []*Developer_Medium {
	if x != nil {
		return x.Mediums
	}
	return nil
}

type Developer_Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cover    string   `protobuf:"bytes,1,opt,name=cover,proto3" json:"cover,omitempty"`
	Movie    string   `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	Pictures []string `protobuf:"bytes,3,rep,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *Developer_Media) Reset() {
	*x = Developer_Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_developer_store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Developer_Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer_Media) ProtoMessage() {}

func (x *Developer_Media) ProtoReflect() protoreflect.Message {
	mi := &file_developer_store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer_Media.ProtoReflect.Descriptor instead.
func (*Developer_Media) Descriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{2}
}

func (x *Developer_Media) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Developer_Media) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

func (x *Developer_Media) GetPictures() []string {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type Developer_Experience struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Experience
	EnableExperience bool   `protobuf:"varint,1,opt,name=enable_experience,json=enableExperience,proto3" json:"enable_experience,omitempty"`
	DeveloperComment string `protobuf:"bytes,2,opt,name=developer_comment,json=developerComment,proto3" json:"developer_comment,omitempty"`
}

func (x *Developer_Experience) Reset() {
	*x = Developer_Experience{}
	if protoimpl.UnsafeEnabled {
		mi := &file_developer_store_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Developer_Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer_Experience) ProtoMessage() {}

func (x *Developer_Experience) ProtoReflect() protoreflect.Message {
	mi := &file_developer_store_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer_Experience.ProtoReflect.Descriptor instead.
func (*Developer_Experience) Descriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{3}
}

func (x *Developer_Experience) GetEnableExperience() bool {
	if x != nil {
		return x.EnableExperience
	}
	return false
}

func (x *Developer_Experience) GetDeveloperComment() string {
	if x != nil {
		return x.DeveloperComment
	}
	return ""
}

type Developer_BUILD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	File     string `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	UpdateAt int64  `protobuf:"varint,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
}

func (x *Developer_BUILD) Reset() {
	*x = Developer_BUILD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_developer_store_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Developer_BUILD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer_BUILD) ProtoMessage() {}

func (x *Developer_BUILD) ProtoReflect() protoreflect.Message {
	mi := &file_developer_store_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer_BUILD.ProtoReflect.Descriptor instead.
func (*Developer_BUILD) Descriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{4}
}

func (x *Developer_BUILD) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Developer_BUILD) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Developer_BUILD) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Developer_BUILD) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type Developer_Medium struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediumType ENUM_Medium `protobuf:"varint,1,opt,name=medium_type,json=mediumType,proto3,enum=tcaplusservice.ENUM_Medium" json:"medium_type,omitempty"`
	MediumUrl  string      `protobuf:"bytes,2,opt,name=medium_url,json=mediumUrl,proto3" json:"medium_url,omitempty"`
}

func (x *Developer_Medium) Reset() {
	*x = Developer_Medium{}
	if protoimpl.UnsafeEnabled {
		mi := &file_developer_store_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Developer_Medium) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer_Medium) ProtoMessage() {}

func (x *Developer_Medium) ProtoReflect() protoreflect.Message {
	mi := &file_developer_store_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer_Medium.ProtoReflect.Descriptor instead.
func (*Developer_Medium) Descriptor() ([]byte, []int) {
	return file_developer_store_proto_rawDescGZIP(), []int{5}
}

func (x *Developer_Medium) GetMediumType() ENUM_Medium {
	if x != nil {
		return x.MediumType
	}
	return ENUM_Medium_official_site
}

func (x *Developer_Medium) GetMediumUrl() string {
	if x != nil {
		return x.MediumUrl
	}
	return ""
}

var File_developer_store_proto protoreflect.FileDescriptor

var file_developer_store_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x63, 0x61, 0x70, 0x6c, 0x75, 0x73,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1d, 0x74, 0x63, 0x61, 0x70, 0x6c, 0x75, 0x73,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x02, 0x0a, 0x0f, 0x64, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x63, 0x61, 0x70, 0x6c,
	0x75, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x72, 0x5f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x63, 0x61, 0x70, 0x6c, 0x75, 0x73, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x12, 0x36, 0x0a,
	0x03, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x63, 0x61,
	0x70, 0x6c, 0x75, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x37, 0x0a, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x63, 0x61, 0x70, 0x6c, 0x75, 0x73, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x52, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x3a, 0x25,
	0x82, 0xa6, 0x1d, 0x0e, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x2c, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x8a, 0xa6, 0x1d, 0x0f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x32, 0x28, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x29, 0x22, 0xb6, 0x02, 0x0a, 0x14, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x72, 0x5f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74,
	0x63, 0x61, 0x70, 0x6c, 0x75, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x62, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x63, 0x61, 0x70, 0x6c, 0x75, 0x73, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x4d,
	0x65, 0x64, 0x69, 0x75, 0x6d, 0x52, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x73, 0x22, 0x59,
	0x0a, 0x0f, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x70, 0x0a, 0x14, 0x44, 0x65, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x66, 0x0a, 0x0f, 0x44,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x22, 0x6f, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x5f, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x3c, 0x0a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x75,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74,
	0x63, 0x61, 0x70, 0x6c, 0x75, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x52, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x75,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x75,
	0x6d, 0x55, 0x72, 0x6c, 0x2a, 0x64, 0x0a, 0x0b, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4d, 0x65, 0x64,
	0x69, 0x75, 0x6d, 0x12, 0x11, 0x0a, 0x0d, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x5f,
	0x73, 0x69, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x66, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x10, 0x03,
	0x12, 0x0b, 0x0a, 0x07, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x10, 0x05, 0x2a, 0x4c, 0x0a, 0x0b, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x65, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x69, 0x6e, 0x67, 0x5f, 0x53, 0x6f, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x10, 0x03, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x3b, 0x74,
	0x63, 0x61, 0x70, 0x6c, 0x75, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_developer_store_proto_rawDescOnce sync.Once
	file_developer_store_proto_rawDescData = file_developer_store_proto_rawDesc
)

func file_developer_store_proto_rawDescGZIP() []byte {
	file_developer_store_proto_rawDescOnce.Do(func() {
		file_developer_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_developer_store_proto_rawDescData)
	})
	return file_developer_store_proto_rawDescData
}

var file_developer_store_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_developer_store_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_developer_store_proto_goTypes = []interface{}{
	(ENUM_Medium)(0),             // 0: tcaplusservice.ENUM_Medium
	(ENUM_Status)(0),             // 1: tcaplusservice.ENUM_Status
	(*DeveloperStore)(nil),       // 2: tcaplusservice.developer_store
	(*Developer_BasicInfo)(nil),  // 3: tcaplusservice.Developer_Basic_info
	(*Developer_Media)(nil),      // 4: tcaplusservice.Developer_Media
	(*Developer_Experience)(nil), // 5: tcaplusservice.Developer_Experience
	(*Developer_BUILD)(nil),      // 6: tcaplusservice.Developer_BUILD
	(*Developer_Medium)(nil),     // 7: tcaplusservice.Developer_Medium
}
var file_developer_store_proto_depIdxs = []int32{
	3, // 0: tcaplusservice.developer_store.info:type_name -> tcaplusservice.Developer_Basic_info
	4, // 1: tcaplusservice.developer_store.medias:type_name -> tcaplusservice.Developer_Media
	5, // 2: tcaplusservice.developer_store.exp:type_name -> tcaplusservice.Developer_Experience
	6, // 3: tcaplusservice.developer_store.builds:type_name -> tcaplusservice.Developer_BUILD
	1, // 4: tcaplusservice.Developer_Basic_info.product_status:type_name -> tcaplusservice.ENUM_Status
	7, // 5: tcaplusservice.Developer_Basic_info.mediums:type_name -> tcaplusservice.Developer_Medium
	0, // 6: tcaplusservice.Developer_Medium.medium_type:type_name -> tcaplusservice.ENUM_Medium
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_developer_store_proto_init() }
func file_developer_store_proto_init() {
	if File_developer_store_proto != nil {
		return
	}
	file_tcaplusservice_optionv1_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_developer_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeveloperStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_developer_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Developer_BasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_developer_store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Developer_Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_developer_store_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Developer_Experience); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_developer_store_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Developer_BUILD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_developer_store_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Developer_Medium); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_developer_store_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_developer_store_proto_goTypes,
		DependencyIndexes: file_developer_store_proto_depIdxs,
		EnumInfos:         file_developer_store_proto_enumTypes,
		MessageInfos:      file_developer_store_proto_msgTypes,
	}.Build()
	File_developer_store_proto = out.File
	file_developer_store_proto_rawDesc = nil
	file_developer_store_proto_goTypes = nil
	file_developer_store_proto_depIdxs = nil
}
