// auto generated by tdr 2.7.37, don't edit!
//
//     go code compiler
//     author: cowhuang@tencent.com
//
// create time: 2021-07-08 12:01:09
package tcaplus_protocol_cs

// Since 3.37.0,it changes from 4 to 8
const TCAPLUS_MAX_KEY_FIELD_NUM int64 = 8

// Since 3.37.0,it changes from 3 to 7
const TCAPLUS_MAX_KEY_FIELD_NUM_LISTTABLE int64 = 7

// value nums
const TCAPLUS_MAX_VALUE_FIELD_NUM int64 = 256

// value nums since 3.46.0 changed to 256
const TCAPLUS_MAX_VALUE_FIELD_NUM_128 int64 = 128

// 分布式索引支持的最大索引字段数，就是TCAPLUS_MAX_KEY_FIELD_NUM+TCAPLUS_MAX_VALUE_FIELD_NUM
const TCAPLUS_MAX_INDEX_FIELD_NUM int64 = 264

// include 0 length
const TCAPLUS_MAX_TABLE_NAME_LEN int64 = 32

// include 0 length
const TCAPLUS_MAX_FIELD_NAME_LEN int64 = 32

// single key max len
const TCAPLUS_MAX_KEY_FIELD_LEN int64 = 1024

// single value max len:256KB tcapsvr>=3.32.0
const TCAPLUS_MAX_VALUE_FIELD_LEN int64 = 262144

// 实际的一个记录的Key所有字段的最大Buff长度应该是比该值小
const TCAPLUS_MAX_KEY_ALL_FIELDS_LEN int64 = 8192
const TCAPLUS_BIG_RECORD_MAX_VALUE_BUF_LEN int64 = 10000000

// 所有value字段buf相加的最大长度, since 3.39.0
const TCAPLUS_MAX_VALUE_ALL_FIELDS_LEN int64 = 10000000
const TCAPLUS_SMALL_RECORD_MAX_VALUE_BUF_LEN int64 = 1000000
const TCAPLUS_PACKAGE_ADDITIONAL_LEN int64 = 400000
const TCAPLUS_BIG_PACKAGE_ADDITIONAL_LEN int64 = 3000000
const TCAPLUS_TSD_SMALL_BUF_LEN int64 = 1400000
const TCAPLUS_MEM_POOL_BIG_BUF_LEN int64 = 10400000

// equal TCAPLUS_MAX_VALUE_ALL_FIELDS_LEN + 200KB
const TCAPLUS_GROSS_MAX_VALUE_BUFFER_LEN int64 = 10200000

// 协议打包BUF最大长度，等于 TCAPLUS_MAX_VALUE_ALL_FIELDS_LEN + TCAPLUS_BIG_PACKAGE_ADDITIONAL_LEN
const TCAPLUS_MAX_PACK_BUF_LEN int64 = 13000000

// equal TCAPLUS_MAX_VALUE_ALL_FIELDS_LEN + 300KB
const TCAPLUS_MAX_BATCH_VALUE_LEN int64 = 10300000

// 多包响应时的分包大小250KB
const TCAPLUS_SPLIT_PACKET_SIZE int64 = 256000
